### PR TITLE
Fix for #97

### PR DESCRIPTION
**Pull request by kmadathil**
Fix for #97 

We should also be able to delete spaces in sandhi rules now if we wish. Thoughts?

### CODE REVIEW

**Comment by avinashvarna** [comment]
I feel like this change conflicts with the changes made for tokenize.
E.g. on master:
```
(master) $ python -m sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer --split "vA vA vA"
Input String: vA vA vA
Input String in SLP1: vA vA vA
Start Split
End DAG generation
End pathfinding 1542690436.52
Splits:
[vAH, vAH, vA]
[vA, vAH, vA]
[vAH, vA, vA]
[vAH, vAH, vA]
[vA, vA, vA]
[vAH, vAH, vA]
[vAH, vA, vA]
[vA, vAH, vA]
[vAH, vAH, vA]
```
Note that there are no cross word splits. Now with this PR:
```
(karthik) $ python -m sanskrit_parser.lexical_analyzer.sanskrit_lexical_analyzer --split "vA vA vA"
Input String: vA vA vA
Input String in SLP1: vA vA vA
Start Split
End DAG generation
End pathfinding 1542690482.72
Splits:
[vAH, vAH, vA]
[va, ava, AvA]
[vAH, va, AvA]
[vA, ava, AvA]
[va, AvA, AvA]
[va, ava, avA]
[vAH, vA, vA]
[vAH, va, avA]
[vAH, va, AvA]
[vA, AvA, AvA]
```
we see `vA ava` type of splits, which are unexpected, IMO.

**Comment by kmadathil** [comment]
Yes, good catch. I was a bit naive about what "split at x" meant in our context. Let's reject this PR.
That would mean going to the "add all pada spaces in sandhi rules" way. Do you agree? @avinashvarna

**Comment by avinashvarna** [comment]
Given that there are no specific rules on where spaces should be used AFAIK (as also discussed in #91 ), and the conventions are changing (such as "ity api"/"harir iha"), IMO, we should not pay any special attention to spaces. This may lead to splits that may seem unexpected (such as vA ava above), but is relied on in a lot of shleshAlankAras in kAvyas.

**Comment by kmadathil** [comment]
Not merging this. Keep the issue of spaces open. I prefer to do a mandatory split at spaces, but we need more thought here

**Pull request closed without merging**
