### PR TITLE
Lexical lookup based on sanskrit_util library

### PR DESCRIPTION
**Pull request by codito**

### CODE REVIEW

**Comment by kmadathil** [comment]
I'm trying to test the merge locally, but I get a couple of failures in lexical analyzer tests. I will debug this.

**Comment by kmadathil** [comment]
@codito - Can you confirm you got the tests running locally before merge? Did you have to regenerate the pass list? 
I do see a pass on Travis-CI, so I must be missing something.

**Comment by codito** [comment]
@kmadathil yes, I had run `tox -e py36`. May be the errors are showing up with full test pass - `pytest tests/test_SanskritLexicalAnalyzer.py`. Let me try this too.

**Comment by kmadathil** [comment]
@codito 
Interesting. I ran on py27 with
pytest --test-count 1000 tests/test_DhatuWrapper.py tests/test_sandhi.py tests/test_SanskritLexicalAnalyer.py

I haven't been able to work on this further last night.

**Comment by avinashvarna** [comment]
Looks like @codito's changes only affect the word accuracy computation and the data printed from the command line. Since most of the changes are mine, I don't know if I am the best person to review these changes ...

**Comment by codito** [comment]
@kmadathil I ran the py27 tests with `tox -e py27` (it runs the same command in a virtualenv). Can you try this? It will install the dependencies cleanly, we can isolate if that's causing errors.

What are the errors you're seeing? May be the stack trace could give us a clue on what's missing.

**Pull request merged**
