### PR TITLE
Fix for #153

### PR DESCRIPTION
**Pull request by kmadathil**
Added SandhiKosh tests
Created test_SandhiKosh.py to run passing SandhiKosh tests
Updated tox.ini to run test_SandhiKosh.py
Removed uohd tests from test_SanskritLexicalAnalyzer.py (since they're in SandhiKosh)

### CODE REVIEW

**Review by avinashvarna — COMMENTED** [review]
I would personally prefer to add the sandhikosh repo as a git submodule, instead of replicating the files. Updating them in case the original repo is updated is then a simple(r) pull, and it is also easier to push any changes upstream, so that others can use them as well. 

I will look at the other changes soon.

**Comment by kmadathil** [comment]
Moved SandhiKosh to submodule

**Comment by kmadathil** [comment]
@avinashvarna Avinash, can we merge this?

**Comment by avinashvarna** [comment]
Looks good to me. Please delete the source branch if it is no longer required.

**Pull request merged**
